sudo: false
services:
- docker
language: rust
rust:
- stable
cache: cargo
before_script:
- wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
- nvm install node
- nvm run node --version
- git clone https://github.com/Roba1993/SPE3D.git
- docker login -u="roba1993" -p="$DOCKER_PASSWORD"
#- docker pull clux/muslrust
script:
#- cargo test
- make docker
- docker run -d -p 127.0.0.1:8000:8000 --name=spe3d -t roba1993/spe3d
- sleep 1
- curl -sSL http://127.0.0.1:8000/api/test | grep "Success"
- docker rm -f spe3d
after_success:
- docker push roba1993/spe3d
after_script:
- docker logout