sudo: false
services:
- docker
language: rust
rust:
- nightly
cache: cargo
before_script:
- sudo apt-get install nodejs npm
- git clone https://github.com/Roba1993/SPE3D.git
- docker login -u="roba1993" -p="$DOCKER_PASSWORD"
#- docker pull clux/muslrust
script:
- cargo test
- make docker
- docker run -d -p 8000:8000 --name=spe3d -t roba1993/spe3d
- sleep 1
- curl -sSL localhost:8000 | grep "Success"
- docker rm -f spe3d
after_success:
- docker push roba1993/spe3d
after_script:
- docker logout