[package]
name = "rdm"
version = "0.1.0"
authors = ["roba"]

[dependencies]
reqwest = "0.8.1"
rust-crypto = "0.2"
regex = "0.2"
rustc-serialize = "0.3"
error-chain = "0.11.0"
dlc-decrypter = {git = "https://github.com/Roba1993/dlc-decoder"}

curl = "0.4.8"
chrono = "0.4"
cookie = "0.10"