[package]
name = "rdm"
version = "0.1.0"
authors = ["roba"]

[dependencies]
reqwest = "0.8.1"
regex = "0.2"
error-chain = "0.11.0"
dlc-decrypter = "0.1"
md-5 = "0.7.0"
digest = { version = "0.7.0", features = ["std"]}