# SPE3D - Configuration

# ip under the webserver should be started
# If you run locally it's localhost or 127.0.0.1
# If you run in docker it's 0.0.0.0
[server]
ip = 'localhost'
webserver_port = 8000
websocket_port = 8001

[[share_online]]
username = 'usr'
password = 'pwd'